version: "3.8"

services:

  chat:
    build:
      context: .
      target: chat_service
    volumes:
      - ./chat_service/:/app/
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8081:8080"

  dispute_management:
    build:
      context: .
      target: dispute_management_service
    volumes:
      - ./dispute_management_service/:/app/
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8082:8080"

  product_inventory:
    build:
      context: .
      target: product_inventory_service
    volumes:
      - ./product_inventory_service/:/app/
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8083:8080"

  reporting_service:
    build:
      context: .
      target: reporting_service
    volumes:
      - ./reporting_service/:/app/
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8084:8080"

  user_management:
    build:
      context: .
      target: user_management_service
    volumes:
      - ./user_management_service/:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JDBC_POSTGRES_URL: jdbc:postgresql://localhost:9085/users
    ports:
      - "8085:9000"
  
  user_management_db:
    image: postgres:13-alpine
    user: postgres
    volumes:
      - ./user_management_service/.postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9085:5432"
